---
pipeline:
  build_image:
    image: docker:17.09.0-ce
    secrets:
      - docker_sysdig_token
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="sysdig+homeoffice" -p=$${DOCKER_SYSDIG_TOKEN} quay.io
      - docker build -t cassandra-sysdig:$${DRONE_COMMIT_SHA} .
 
  image_to_repo:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="sysdig_drone" -p=$${DOCKER_PASSWORD} docker.digital.homeoffice.gov.uk
      - docker tag cassandra-sysdig:$${DRONE_COMMIT_SHA} docker.digital.homeoffice.gov.uk/cassandra-sysdig:$${DRONE_COMMIT_SHA}
      - docker tag cassandra-sysdig:$${DRONE_COMMIT_SHA} docker.digital.homeoffice.gov.uk/cassandra-sysdig:latest
      - docker push docker.digital.homeoffice.gov.uk/cassandra-sysdig:$${DRONE_COMMIT_SHA}
      - docker push docker.digital.homeoffice.gov.uk/cassandra-sysdig:latest
    when:
      event: push
      branch: master

  image_to_repo_on_tag:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="sysdig_drone" -p=$${DOCKER_PASSWORD} docker.digital.homeoffice.gov.uk
      - docker tag cassandra-sysdig:$${DRONE_COMMIT_SHA} docker.digital.homeoffice.gov.uk/cassandra-sysdig:$${DRONE_TAG}
      - docker push docker.digital.homeoffice.gov.uk/cassandra-sysdig:$${DRONE_TAG}
    when:
      event: tag
