---
pipeline:
  build_image:
    privileged: true
    image: docker:1.13
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="sysdig+homeoffice" -p=${DOCKER_SYSDIG_TOKEN} quay.io
      - docker build -t cassandra-sysdig .

  image_to_repo:
    commands:
      - docker login -u="sysdig_drone" -p=${DOCKER_PASSWORD} docker.digital.homeoffice.gov.uk
      - docker tag cassandra-sysdig docker.digital.homeoffice.gov.uk/cassandra-sysdig:latest
      - docker push docker.digital.homeoffice.gov.uk/cassandra-sysdig:latest
    environment:
      - "DOCKER_HOST=tcp://127.0.0.1:2375"
    image: docker:1.13
    when:
      event: push

  image_to_repo_on_tag:
    commands:
      - docker login -u="sysdig_drone" -p=${DOCKER_PASSWORD} docker.digital.homeoffice.gov.uk
      - docker tag cassandra-sysdig docker.digital.homeoffice.gov.uk/cassandra-sysdig:${DRONE_TAG}
      - docker push docker.digital.homeoffice.gov.uk/cassandra-sysdig:${DRONE_TAG}
    environment:
      - "DOCKER_HOST=tcp://127.0.0.1:2375"
    image: docker:1.13
    when:
      event: tag

services:
  dind:
    image: docker:1.13-dind
    privileged: true
    command:
      - "-s"
      - "overlay"
